export type SystemKey =
  | "acquisition"
  | "surface"
  | "google"
  | "automation"
  | "crm"
  | "reporting"
  | "governance";

export type StatusKey = "live" | "ready" | "planned" | "external" | "legacy";
export type EdgeMode = "browser" | "server" | "business" | "report" | "planned";

export type TrackingItem = {
  id: string;
  title: string;
  technicalName?: string;
  technicalId?: string;
  system: SystemKey;
  status: StatusKey;
  owner: string;
  phase: string;
  summary: string;
  receives: string;
  sends: string;
  check: string;
  rollback: string;
  location?: string;
  href?: string;
  searchTerms?: string;
};

export type ViewKey =
  | "overview"
  | "visit"
  | "lead"
  | "events"
  | "attribution"
  | "reporting"
  | "roadmap";

export type NodeSpec = {
  id: string;
  itemId: string;
  x: number;
  y: number;
  width?: number;
};

export type EdgeSpec = {
  id: string;
  source: string;
  target: string;
  label?: string;
  mode: EdgeMode;
};

export type TrackingView = {
  label: string;
  title: string;
  description: string;
  focus: string;
  nodes: NodeSpec[];
  edges: EdgeSpec[];
};

export const verifiedAt = "15 августа 2026";

export const systemLabels: Record<SystemKey, string> = {
  acquisition: "Источники",
  surface: "Поверхности",
  google: "Google",
  automation: "n8n и передача",
  crm: "CRM и доказательства",
  reporting: "Отчётность",
  governance: "Правила и владельцы",
};

export const statusLabels: Record<StatusKey, string> = {
  live: "Работает",
  ready: "Подготовлено",
  planned: "Следующий этап",
  external: "Внешняя зависимость",
  legacy: "Выводится",
};

export const edgeLabels: Record<EdgeMode, string> = {
  browser: "в браузере",
  server: "на сервере",
  business: "бизнес-факт",
  report: "в отчёт",
  planned: "следующий этап",
};

export const items: TrackingItem[] = [
  {
    id: "traffic-sources",
    title: "Реклама, органика и прямые визиты",
    technicalName: "source / campaign / referrer / direct",
    system: "acquisition",
    status: "live",
    owner: "Владельцы рекламных и органических каналов",
    phase: "Вход в систему",
    summary: "Начало пользовательского пути. Источник определяется по доказательствам, а не по названию страницы или рекламного кабинета.",
    receives: "Клик или прямой переход пользователя.",
    sends: "UTM, рекламные click ID, referrer и адрес входной страницы.",
    check: "Открыть тестовый URL и убедиться, что параметры дошли до страницы, data layer и следующей поверхности.",
    rollback: "Не применяется: источник не изменяется tracking-контуром.",
    searchTerms: "google youtube meta facebook seo utm gclid gbraid wbraid fbclid direct unknown",
  },
  {
    id: "web-surfaces",
    title: "Сайты и посадочные GetsMine",
    technicalName: "getsmine.io · GHL · Tilda · join · promo · quiz",
    system: "surface",
    status: "live",
    owner: "Tracking вместе с владельцем конкретной поверхности",
    phase: "Маршрут посещения",
    summary: "Публичные страницы принимают визит, сохраняют параметры входа и передают web-поведение в основной аналитический контур.",
    receives: "URL, UTM, referrer, click ID и действия пользователя.",
    sends: "Page view, data layer events и контекст формы; бизнес-факт формы передаётся отдельным маршрутом.",
    check: "Tag Assistant, сетевые запросы и контроль сохранения URL-параметров между страницами.",
    rollback: "Вернуть предыдущую опубликованную конфигурацию конкретной поверхности.",
    location: "www.getsmine.io, join.getsmine.io и другие публичные поверхности",
  },
  {
    id: "customer-portal",
    title: "Личный кабинет GetsMine",
    technicalName: "customers.getsmine.io",
    system: "surface",
    status: "external",
    owner: "Продуктовая разработка; tracking задаёт договор событий",
    phase: "Следующий этап: регистрация и trial",
    summary: "Часть общего пользовательского пути и будущий доказанный источник событий регистрации и начала trial.",
    receives: "Переход пользователя с сайта и действия внутри продукта.",
    sends: "В будущем: sign_up, start_trial, стабильный non-PII user ID и GA client/session ID.",
    check: "Проверить реальный backend-факт регистрации или trial, затем Trace и GA4.",
    rollback: "Отключить новый source adapter, сохранив действующий продуктовый процесс.",
    location: "customers.getsmine.io",
    searchTerms: "sign_up start_trial platform user_id CSP",
  },
  {
    id: "calendly",
    title: "Calendly и календари GHL",
    technicalName: "calendly.getsmine.io · GHL Calendar",
    system: "surface",
    status: "live",
    owner: "Tracking и владелец календарного процесса",
    phase: "Поведение сейчас; встреча позже",
    summary: "Загрузка календаря остаётся поведением, а не лидом и не доказанной встречей. Будущая встреча появится только из уникального appointment event.",
    receives: "Переход после формы и сохранённые UTM.",
    sends: "Обычные page_view; позднее — доказанный appointment event через корпоративный n8n.",
    check: "Проверить, что загрузка /he не создаёт key event и что UTM сохраняются после перехода.",
    rollback: "Вернуть предыдущее правило только через отдельную зафиксированную публикацию.",
    location: "calendly.getsmine.io/he",
  },
  {
    id: "firebase-app",
    title: "Мобильное приложение",
    technicalName: "Firebase / iOS / Android",
    system: "surface",
    status: "planned",
    owner: "Продуктовая разработка и tracking",
    phase: "Отдельный будущий контур",
    summary: "Native app остаётся отдельным Firebase-контуром и не смешивается с web stream без проверки SDK, релизов и договора событий.",
    receives: "Действия пользователя в мобильном приложении.",
    sends: "Будущие app events и согласованные бизнес-события.",
    check: "Проверить production SDK, app streams и соответствие общему словарю событий.",
    rollback: "Не подключать app destinations к основному web stream до отдельного решения.",
  },
  {
    id: "main-gtm",
    title: "Основной контейнер тегов",
    technicalName: "Google Tag Manager",
    technicalId: "GTM-TVT4CX9D",
    system: "google",
    status: "live",
    owner: "Tracking",
    phase: "Маршрут посещения",
    summary: "Единая опубликованная конфигурация web-тегов для управляемых first-party поверхностей GetsMine.",
    receives: "Page context, data layer events, consent state и идентификаторы браузерной сессии.",
    sends: "Основной GA4 stream и объединённый Google Ads tag.",
    check: "Preview / Tag Assistant на каждом затронутом домене, затем контроль свежего публичного gtm.js.",
    rollback: "Повторно опубликовать GTM version 43; текущая рабочая версия — 44.",
    location: "GTM account 6215719835",
  },
  {
    id: "main-ga4",
    title: "Основная Google Analytics",
    technicalName: "GA4 Property GetsMine · Web stream",
    technicalId: "Property 426661253 · G-E5E152Q3Q0",
    system: "google",
    status: "live",
    owner: "Tracking",
    phase: "Digital journey и web attribution",
    summary: "Главный аналитический контур GetsMine. Он показывает цифровой путь и принимает только доказанные server events в дополнение к browser tracking.",
    receives: "Web-события из GTM и назначенные server events из корпоративного n8n.",
    sends: "Аналитические отчёты, key events и согласованные связи с Google Ads.",
    check: "Realtime / DebugView, затем обычные отчёты после обработки.",
    rollback: "Для GTM-событий вернуть предыдущую container version; GA4 Admin changes откатывать по журналу 2.7.",
    location: "GA Account 301787226 · stream resource 6711032517",
  },
  {
    id: "combined-ads-tag",
    title: "Единый Google Ads tag",
    technicalName: "Google tag with Ads destinations",
    technicalId: "GT-PBZ4WBXN",
    system: "google",
    status: "live",
    owner: "Tracking и Google Ads owner",
    phase: "Оптимизация рекламы",
    summary: "Один стандартный Google tag заменил два ручных Custom HTML loader и связан с действующими Ads destinations.",
    receives: "Web-сигналы из основного GTM.",
    sends: "Разрешённые сигналы в Google Ads; accepted lead текущего GHL-пути остаётся отдельным действием.",
    check: "Tag Assistant должен показывать один запуск; Google Ads diagnostics — правильную destination.",
    rollback: "Повторно опубликовать GTM version 43.",
  },
  {
    id: "legacy-tags",
    title: "Старые и дублирующие теги",
    technicalName: "G-JWTSLL7RXD · G-Z65YBQ6T69 · Custom HTML Ads loaders",
    system: "google",
    status: "legacy",
    owner: "Tracking",
    phase: "Пакет 2 завершён",
    summary: "Поставлены на паузу после доказанной замены. История и версия 43 сохранены для отката.",
    receives: "Раньше получали все page views или отдельные VSL-визиты.",
    sends: "Сейчас ничего: запуск отключён в live GTM version 44.",
    check: "Публичный контейнер и чистый браузер не должны загружать старые measurement IDs.",
    rollback: "Повторно опубликовать GTM version 43.",
  },
  {
    id: "accepted-form",
    title: "Принятая заявка Google / YouTube",
    technicalName: "Israel Google - Call Back Form",
    technicalId: "GHL workflow 8d529a6f-40e6-48ac-8f4e-dd3e197bb677",
    system: "surface",
    status: "live",
    owner: "GHL owner; tracking владеет аналитическим отображением",
    phase: "Первый доказанный бизнес-факт",
    summary: "Заполненная и принятая форма текущих Google / YouTube лендингов считается новым лидом.",
    receives: "Контакт, attribution context, landing URL, UTM и реальный gaClientId.",
    sends: "Контакт в GHL, CRM-маршрут, Pipedrive deal и два раздельных назначения: GA4 и Google Ads.",
    check: "Контрольная отправка формы должна создать одну сделку, одну Trace-запись и одно generate_lead.",
    rollback: "Вернуть предыдущую опубликованную версию GHL workflow.",
    location: "join.getsmine.io/israel-b2b-funnel-670531 и три родственных лендинга",
  },
  {
    id: "corporate-n8n",
    title: "Корпоративный маршрут нового лида",
    technicalName: "GHL Event Created Refactor by Sandr V2",
    technicalId: "PLkOwObujA4l8euK",
    system: "automation",
    status: "live",
    owner: "CRM владеет маршрутом; tracking — веткой отправки в GA4",
    phase: "Нормализация и доставка",
    summary: "Существующий CRM-процесс создаёт или связывает сделку, формирует Trace и параллельно передаёт доказанный результат в tracking sender.",
    receives: "GHL payload и созданный deal_id.",
    sends: "Lead Attribution Trace, Pipedrive и нормализованный trace-объект в GA4 sender.",
    check: "Проверить успешные executions родителя, child workflow и sender без изменения текущих Meta и других входов.",
    rollback: "Активировать предыдущую версию 7ac5b948-dfe9-45c6-a66e-51c97fb5f73a.",
  },
  {
    id: "trace",
    title: "Доказательство происхождения лида",
    technicalName: "Lead Attribution Trace",
    technicalId: "WvjzpXT2qkEdAITz · 65 полей",
    system: "crm",
    status: "live",
    owner: "Совместный CRM / tracking-контур; schema и writer меняет CRM owner",
    phase: "Общий доказательный слой",
    summary: "Хранит исходное доказательство, идентификаторы, FT/LT, решение CRM и связь со сделкой. Не заменяет Pipedrive или GA4.",
    receives: "Нормализованные события из действующих source routes через общий writer.",
    sends: "Доказательства CRM, destination senders и подготовленные читательские слои.",
    check: "Сверить trace key, deal/person links, attribution evidence и наличие реальных GA client/session ID.",
    rollback: "Schema и writer откатываются только CRM-владельцем с проверкой зависимых процессов.",
    location: "Corporate n8n Data Table",
    searchTerms: "FT LT first touch last touch ga_client_id ga_session_id evidence",
  },
  {
    id: "pipedrive",
    title: "Работа продаж с новым лидом",
    technicalName: "Pipedrive Person · Deal · Activity",
    system: "crm",
    status: "live",
    owner: "CRM и продажи",
    phase: "Коммерческая работа",
    summary: "Pipedrive получает только новый лид, когда CRM-классификация это разрешает. Он хранит компактные FT/LT и работу продаж, но не весь multi-touch путь.",
    receives: "Нормализованный новый лид и принятую attribution-классификацию.",
    sends: "Стадии, активности, результат сделки и данные подготовленному CRM-слою.",
    check: "Сверить person/deal, UTM, источник, отсутствие лишней сделки для существующего клиента.",
    rollback: "Отключить новый source adapter или sender, не переписывая действующие CRM-данные.",
  },
  {
    id: "source-map",
    title: "Единая CRM-карта источников",
    technicalName: "crm-source-field-map.md",
    system: "governance",
    status: "live",
    owner: "CRM owner",
    phase: "Человекочитаемая классификация",
    summary: "Определяет, как доказательства Trace превращаются в источник, поверхность входа, способ создания сделки и управленческий статус.",
    receives: "Поля Trace, Pipedrive и правила нормализации.",
    sends: "Единое решение в Leads, Sources, Weekly и Dashboard.",
    check: "Один и тот же лид должен иметь совместимую классификацию во всех читательских таблицах.",
    rollback: "Вернуть предыдущую принятую карту и её исполняемые правила через CRM-контур.",
  },
  {
    id: "ga4-sender",
    title: "Отправка подтверждённого лида в GA4",
    technicalName: "GM Tracking - GA4 Generate Lead Sender v0.1",
    technicalId: "Ye7Tfy3ytvgcAlar",
    system: "automation",
    status: "live",
    owner: "Tracking",
    phase: "Пакет 3 завершён",
    summary: "Отправляет ровно один generate_lead только для доказанного GHL-маршрута и не выдумывает отсутствующий session ID.",
    receives: "Нормализованный trace после создания deal_id, реальный ga_client_id и бизнес-контекст формы.",
    sends: "GA4 Measurement Protocol event с шестью низкокардинальными бизнес-параметрами.",
    check: "Delivery status sent, HTTP 204 и ровно один generate_lead в GA4 Realtime.",
    rollback: "Отключить узел Send Accepted Lead To GA4 и вернуть старое GHL GA4-действие только как согласованный откат.",
    href: "https://relay.getsmine.io/workflow/Ye7Tfy3ytvgcAlar",
  },
  {
    id: "delivery-log",
    title: "Контроль доставки аналитических событий",
    technicalName: "GM Tracking Event Delivery",
    technicalId: "q16xa3qNznnRd43z",
    system: "automation",
    status: "live",
    owner: "Tracking",
    phase: "Защита от повторов",
    summary: "Отдельный tracking-журнал не даёт повторной доставке создать вторую конверсию и сохраняет ошибку для повторной попытки.",
    receives: "Устойчивый ключ события и результат запроса к назначению.",
    sends: "Статус sent или failed, время и execution ID без PII и полного payload.",
    check: "Повтор того же ключа должен остановиться до второго запроса; failed допускает retry.",
    rollback: "Отключить sender; таблица остаётся журналом уже выполненных попыток.",
  },
  {
    id: "generate-lead",
    title: "Новый лид создан",
    technicalName: "generate_lead",
    system: "google",
    status: "live",
    owner: "Tracking",
    phase: "Событие первой версии",
    summary: "Первое полностью доказанное бизнес-событие архитектуры. Сейчас его источником является принятая GHL-форма Google / YouTube.",
    receives: "Доказанный accepted form, ga_client_id и нормализованные бизнес-параметры.",
    sends: "Основной GA4 key event и текущий основной Google Ads accepted-lead signal.",
    check: "Один реальный лид — одно событие в Realtime и одна запись доставки.",
    rollback: "Отключить новый server sender и восстановить предыдущий согласованный способ доставки.",
    searchTerms: "lead_type entry_surface form_name page_group pipeline_target routing_country",
  },
  {
    id: "custom-definitions",
    title: "Понятные разрезы по лидам",
    technicalName: "GA4 event-scoped custom dimensions",
    technicalId: "lead_type · entry_surface · form_name · page_group · pipeline_target · routing_country",
    system: "google",
    status: "live",
    owner: "Tracking",
    phase: "Пакет 3 завершён",
    summary: "Шесть бизнес-разрезов позволяют анализировать лиды без email, телефона, CRM ID и других высококардинальных технических полей.",
    receives: "Одноимённые параметры реально поступившего generate_lead.",
    sends: "Измерения для обычных GA4-отчётов после стандартной обработки.",
    check: "Сначала Realtime / DebugView, затем значения в обычных отчётах; история до создания definitions не восстанавливается.",
    rollback: "Удаление definition не удаляет уже собранный event; решение фиксируется отдельно в GA4 Admin-журнале.",
  },
  {
    id: "google-ads-lead",
    title: "Основная конверсия Google Ads",
    technicalName: "Accepted GHL lead",
    technicalId: "Conversion action 7721002970",
    system: "google",
    status: "live",
    owner: "Google Ads owner; tracking доказывает сигнал",
    phase: "Оптимизация текущей кампании",
    summary: "Реклама получает принятый лид как основной сигнал. Загрузка Calendly и form_start больше не входят в основные конверсии.",
    receives: "Отдельное GHL Google Ads action после принятой формы.",
    sends: "Primary conversion в campaign custom goal текущей YouTube-кампании.",
    check: "Google Ads action 7721002970 остаётся primary; ложные actions — secondary.",
    rollback: "Возврат biddable-настроек ложных actions возможен по журналу пакета 1, но не требуется для текущего маршрута.",
  },
  {
    id: "sign-up",
    title: "Регистрация завершена",
    technicalName: "sign_up",
    system: "google",
    status: "planned",
    owner: "Платформа подтверждает факт; tracking доставляет",
    phase: "Этап 3",
    summary: "Событие появится только из доказанного факта создания аккаунта, а не из клика или старого data layer имени с другим регистром.",
    receives: "Backend event регистрации, event ID, platform_user_id и доступные GA identifiers.",
    sends: "Trace и основной GA4.",
    check: "Одна регистрация создаёт одно sign_up и не создаёт лишнюю Pipedrive-сделку для существующего клиента.",
    rollback: "Отключить новый source adapter / sender, сохранив текущую платформу.",
  },
  {
    id: "start-trial",
    title: "Пробный период действительно начался",
    technicalName: "start_trial",
    system: "google",
    status: "planned",
    owner: "Платформа подтверждает факт; tracking доставляет",
    phase: "Этап 3",
    summary: "Отдельный бизнес-факт после регистрации. Старый click_Trial не принимается как доказательство фактической активации trial.",
    receives: "Backend event начала trial и устойчивый event ID.",
    sends: "Trace, основной GA4 и позднее согласованный рекламный сигнал.",
    check: "Регистрация и trial должны остаться двумя разными событиями и не перезаписывать друг друга.",
    rollback: "Отключить новый source adapter / sender.",
  },
  {
    id: "future-outcomes",
    title: "Встреча, квалификация, сделка и оплата",
    technicalName: "meeting / qualify_lead / deal outcome / purchase",
    system: "crm",
    status: "planned",
    owner: "CRM, продажи, платформа и tracking по принятому источнику факта",
    phase: "Этап 5",
    summary: "Поздние результаты возвращаются только после определения доказанного бизнес-факта. Стадия или сумма сами по себе не объявляются оплатой.",
    receives: "Уникальные appointment events, проверенные поля качества, исход сделки и системное платёжное событие.",
    sends: "Trace, GA4, Google Ads и управленческую отчётность по назначению.",
    check: "Каждый результат прослеживается от исходной системы до всех назначений без дублей.",
    rollback: "Отключить конкретный destination sender, сохранив доказательство в Trace.",
  },
  {
    id: "attribution-contract",
    title: "Правило определения источника",
    technicalName: "UTM → referrer → direct → unknown",
    system: "governance",
    status: "live",
    owner: "Tracking задаёт правило; CRM применяет классификацию",
    phase: "Общий договор",
    summary: "Каждая CRM-запись получает источник. Техническая потеря данных не маскируется под direct, а отмечается unknown для разбора.",
    receives: "FT/LT UTM, referrer, click IDs и evidence quality.",
    sends: "FT на Person, LT на Deal, полный след в Trace и digital journey в GA4.",
    check: "По одной заявке восстановить источник, первую и последнюю точки, click ID и причину unknown.",
    rollback: "Вернуть предыдущую принятую CRM-карту источников через владельца CRM.",
    searchTerms: "first touch last touch person deal multi-touch",
  },
  {
    id: "prepared-crm",
    title: "Подготовленный CRM-слой",
    technicalName: "crm_deals_prepared_latest",
    system: "reporting",
    status: "live",
    owner: "Личный n8n / CRM reporting",
    phase: "Читательский слой",
    summary: "Собирает принятую CRM-классификацию для управленческих таблиц, не переписывая первичное доказательство Trace.",
    receives: "Pipedrive, Trace и CRM-карту источников.",
    sends: "Leads, Sources, Weekly и Dashboard.",
    check: "Сверить реальные лиды и постоянное исключение технических тестов.",
    rollback: "Вернуть предыдущую версию читательского процесса без изменения Trace и Pipedrive.",
  },
  {
    id: "management-reports",
    title: "Управленческие отчёты",
    technicalName: "Leads · Sources · Weekly · Dashboard",
    system: "reporting",
    status: "live",
    owner: "CRM reporting и владельцы маркетинга",
    phase: "Решение по лидам",
    summary: "Показывают нормализованные лиды и источники. Технические тесты остаются в доказательном слое, но исключаются из управленческих цифр.",
    receives: "Подготовленный CRM-слой и согласованные рекламные расходы.",
    sends: "Число лидов, источники, динамику и управленческие показатели.",
    check: "Один набор правил должен давать совместимый результат во всех четырёх читателях.",
    rollback: "Вернуть предыдущий reader и повторно выполнить штатное обновление.",
  },
  {
    id: "ad-costs",
    title: "Расход и показатели рекламных платформ",
    technicalName: "Google Ads / Meta Ads APIs",
    system: "reporting",
    status: "ready",
    owner: "Владельцы рекламы и reporting",
    phase: "Подключение к общей отчётности",
    summary: "Расход берётся из рекламной системы, а число реальных лидов — из нормализованного CRM-слоя. Эти источники сверяются, а не заменяют друг друга.",
    receives: "Показы, клики, расход и платформенные конверсии из рекламных API.",
    sends: "CPL и рекламные показатели в общий Dashboard после согласования валют и периода.",
    check: "Сверить рекламный кабинет, валюту, период и отличие Ads conversions от CRM leads.",
    rollback: "Отключить новый reporting reader, сохранив текущие рекламные и CRM-данные.",
  },
  {
    id: "revenue-reporting",
    title: "Сквозной результат до выручки",
    technicalName: "source → visit → sign_up → lead → trial → revenue",
    system: "reporting",
    status: "planned",
    owner: "Tracking, CRM, финансы и management reporting",
    phase: "Этапы 5–7",
    summary: "Конечная цель: видеть не только заявки, а вклад источника и кампании во встречу, квалификацию, сделку, оплату и выручку.",
    receives: "Расходы, digital journey, Trace, CRM outcomes и доказанные финансовые события.",
    sends: "Единые управленческие отчёты и обратные сигналы рекламным системам.",
    check: "Один результат должен прослеживаться до источника, события, CRM и финансового доказательства.",
    rollback: "Каждый новый источник или sender отключается независимо; первичные доказательства сохраняются.",
  },
  {
    id: "consent",
    title: "Consent Mode и управление cookies",
    technicalName: "Osano + Google Consent Mode v2",
    system: "governance",
    status: "external",
    owner: "Отдельное бизнес-решение; затем tracking и разработка",
    phase: "На паузе до решения",
    summary: "Техническая задача подготовлена, но новый баннер и изменение consent state не включаются без отдельного решения о пользовательском интерфейсе.",
    receives: "Решение по использованию действующего Osano и требованиям для текущих стран.",
    sends: "Consent state до запуска аналитических и рекламных тегов.",
    check: "После решения проверить default/update state и поведение тегов при согласии и отказе.",
    rollback: "Вернуть прежнюю конфигурацию и не показывать новый интерфейс без согласования.",
    location: "Platrum 8231",
  },
  {
    id: "redirect-task",
    title: "Сохранить путь и рекламные метки при redirect",
    technicalName: "www.getsmine.io → getsmine.io",
    system: "governance",
    status: "external",
    owner: "Разработка / Cloudflare; tracking проверяет результат",
    phase: "Внешняя задача",
    summary: "Текущий redirect теряет путь и query string, поэтому может обрывать атрибуцию до загрузки сайта.",
    receives: "Исходный URL с path, UTM и click IDs.",
    sends: "Тот же path и все параметры на основном домене.",
    check: "Проверить главную и внутреннюю страницу с UTM, gclid/gbraid/wbraid/fbclid и будущими параметрами.",
    rollback: "Вернуть прежнее redirect rule, если новый маршрут нарушит доступность сайта.",
    location: "Platrum 8229",
  },
  {
    id: "csp-task",
    title: "Разрешить нужные Google-запросы в личном кабинете",
    technicalName: "Content Security Policy на customers.getsmine.io",
    system: "governance",
    status: "external",
    owner: "Разработка; tracking проверяет браузером",
    phase: "На паузе из-за SEO-переезда",
    summary: "На текущем customers-домене часть Google-запросов блокируется. Исправление привязывается к согласованной карте URL после SEO-переезда.",
    receives: "Точную целевую архитектуру доменов и фактические blocked resources.",
    sends: "Узкие CSP-разрешения для нужных Google endpoints без отключения защиты целиком.",
    check: "На целевом URL не должно быть CSP violations; нужные requests должны завершаться успешно.",
    rollback: "Вернуть предыдущую CSP и остановить изменение при расширении доступа сверх согласованного списка.",
    location: "Platrum 8230",
  },
  {
    id: "measurement-best-practices",
    title: "Правило выпуска и отката",
    technicalName: "workspace → preview → realtime → publish → verify → rollback",
    system: "governance",
    status: "live",
    owner: "Tracking",
    phase: "Эксплуатация",
    summary: "Изменения выходят небольшими пакетами с фактической проверкой назначения и готовым возвратом к предыдущей версии.",
    receives: "Ограниченный набор связанных изменений и критерий бизнес-приёмки.",
    sends: "Именованную версию, журнал до/после, контрольный тест и способ отката.",
    check: "Проверить workspace, affected domains, Realtime/DebugView и обычные отчёты после обработки.",
    rollback: "Повторно опубликовать предыдущую GTM version или применить точный GA4 Admin rollback из журнала.",
  },
];

export const itemById = new Map(items.map((item) => [item.id, item]));

const n = (id: string, itemId: string, x: number, y: number, width = 292): NodeSpec => ({ id, itemId, x, y, width });
const e = (id: string, source: string, target: string, mode: EdgeMode, label?: string): EdgeSpec => ({ id, source, target, mode, label });

export const views: Record<ViewKey, TrackingView> = {
  overview: {
    label: "Общая система",
    title: "От источника до управленческого результата",
    description: "Три связанных маршрута: посещение, доказанное бизнес-событие и результат в отчётности.",
    focus: "Главный вопрос: где возникает доказательство и как оно доходит до аналитики, CRM и рекламы.",
    nodes: [
      n("o-source", "traffic-sources", 0, 150),
      n("o-surfaces", "web-surfaces", 310, 0),
      n("o-form", "accepted-form", 310, 300),
      n("o-gtm", "main-gtm", 620, 0),
      n("o-n8n", "corporate-n8n", 620, 300),
      n("o-ga4", "main-ga4", 930, 0),
      n("o-trace", "trace", 930, 300),
      n("o-pipe", "pipedrive", 1240, 390),
      n("o-reports", "management-reports", 1240, 120),
      n("o-revenue", "revenue-reporting", 1550, 120),
    ],
    edges: [
      e("oe1", "o-source", "o-surfaces", "browser", "визит"),
      e("oe2", "o-source", "o-form", "browser", "рекламный клик"),
      e("oe3", "o-surfaces", "o-gtm", "browser", "web-поведение"),
      e("oe4", "o-gtm", "o-ga4", "browser", "digital journey"),
      e("oe5", "o-form", "o-n8n", "business", "принятая форма"),
      e("oe6", "o-n8n", "o-trace", "server", "доказательство"),
      e("oe7", "o-n8n", "o-ga4", "server", "generate_lead"),
      e("oe8", "o-trace", "o-pipe", "business", "новый лид"),
      e("oe9", "o-pipe", "o-reports", "report", "CRM-результат"),
      e("oe10", "o-trace", "o-reports", "report", "источник"),
      e("oe11", "o-reports", "o-revenue", "planned", "следующие outcomes"),
    ],
  },
  visit: {
    label: "Посещение",
    title: "Маршрут визита и web-аналитики",
    description: "Как сохраняются источник, сессия и поведение пользователя на разных поверхностях GetsMine.",
    focus: "Page view показывает поведение; бизнес-конверсия появляется только после доказанного действия.",
    nodes: [
      n("v-source", "traffic-sources", 0, 150),
      n("v-redirect", "redirect-task", 300, 0),
      n("v-web", "web-surfaces", 300, 300),
      n("v-customers", "customer-portal", 600, 0),
      n("v-cal", "calendly", 600, 300),
      n("v-gtm", "main-gtm", 900, 150),
      n("v-ads", "combined-ads-tag", 1200, 0),
      n("v-ga4", "main-ga4", 1200, 300),
      n("v-legacy", "legacy-tags", 1500, 0),
      n("v-csp", "csp-task", 1500, 300),
      n("v-consent", "consent", 1800, 150),
    ],
    edges: [
      e("ve1", "v-source", "v-redirect", "browser", "www-вход"),
      e("ve2", "v-source", "v-web", "browser", "прямой URL"),
      e("ve3", "v-redirect", "v-web", "planned", "сохранить path + query"),
      e("ve4", "v-web", "v-customers", "browser", "путь клиента"),
      e("ve5", "v-web", "v-cal", "browser", "после формы"),
      e("ve6", "v-web", "v-gtm", "browser", "data layer"),
      e("ve7", "v-customers", "v-gtm", "browser", "тот же journey"),
      e("ve8", "v-cal", "v-gtm", "browser", "page_view"),
      e("ve9", "v-gtm", "v-ads", "browser", "один Google tag"),
      e("ve10", "v-gtm", "v-ga4", "browser", "основной stream"),
      e("ve11", "v-legacy", "v-gtm", "planned", "заменены"),
      e("ve12", "v-csp", "v-customers", "planned", "после карты URL"),
      e("ve13", "v-consent", "v-gtm", "planned", "до запуска тегов"),
    ],
  },
  lead: {
    label: "Новый лид",
    title: "Доказанный путь текущей GHL-заявки",
    description: "Работающий пилот: одна принятая форма создаёт одну сделку и один generate_lead без повторов.",
    focus: "Этот маршрут уже проверен production-заявкой и является образцом для следующих source adapters.",
    nodes: [
      n("l-source", "traffic-sources", 0, 160),
      n("l-form", "accepted-form", 300, 160),
      n("l-n8n", "corporate-n8n", 600, 160),
      n("l-trace", "trace", 900, 0),
      n("l-pipe", "pipedrive", 900, 320),
      n("l-sender", "ga4-sender", 1200, 0),
      n("l-delivery", "delivery-log", 1500, 0),
      n("l-ga4", "generate-lead", 1800, 0),
      n("l-ads", "google-ads-lead", 1200, 320),
      n("l-reports", "management-reports", 1500, 320),
    ],
    edges: [
      e("le1", "l-source", "l-form", "browser", "UTM + click ID"),
      e("le2", "l-form", "l-n8n", "business", "accepted form"),
      e("le3", "l-n8n", "l-trace", "server", "trace object"),
      e("le4", "l-n8n", "l-pipe", "business", "deal_id"),
      e("le5", "l-trace", "l-sender", "server", "ga_client_id + context"),
      e("le6", "l-sender", "l-delivery", "server", "dedupe + status"),
      e("le7", "l-delivery", "l-ga4", "server", "один event"),
      e("le8", "l-form", "l-ads", "business", "отдельное Ads action"),
      e("le9", "l-pipe", "l-reports", "report", "CRM-лид"),
      e("le10", "l-trace", "l-reports", "report", "источник"),
    ],
  },
  events: {
    label: "События",
    title: "Словарь бизнес-событий и очереди внедрения",
    description: "В первой версии три разных факта; поздние результаты добавляются только после доказательства.",
    focus: "Одно имя означает один бизнес-факт, а не удобный клик, stage или загрузку страницы.",
    nodes: [
      n("e-platform", "customer-portal", 0, 60),
      n("e-form", "accepted-form", 0, 340),
      n("e-signup", "sign-up", 300, 0),
      n("e-lead", "generate-lead", 300, 220),
      n("e-trial", "start-trial", 300, 440),
      n("e-trace", "trace", 620, 220),
      n("e-defs", "custom-definitions", 940, 60),
      n("e-ga4", "main-ga4", 940, 380),
      n("e-future", "future-outcomes", 1260, 220),
      n("e-revenue", "revenue-reporting", 1580, 220),
    ],
    edges: [
      e("ee1", "e-platform", "e-signup", "planned", "backend fact"),
      e("ee2", "e-form", "e-lead", "business", "accepted form"),
      e("ee3", "e-platform", "e-trial", "planned", "trial activated"),
      e("ee4", "e-signup", "e-trace", "planned", "event contract"),
      e("ee5", "e-lead", "e-trace", "business", "доказательство"),
      e("ee6", "e-trial", "e-trace", "planned", "event contract"),
      e("ee7", "e-trace", "e-defs", "server", "business params"),
      e("ee8", "e-trace", "e-ga4", "server", "server events"),
      e("ee9", "e-trace", "e-future", "planned", "поздние факты"),
      e("ee10", "e-future", "e-revenue", "planned", "outcomes + money"),
    ],
  },
  attribution: {
    label: "Атрибуция",
    title: "Где хранится источник и как он используется",
    description: "UTM, referrer и click IDs сохраняются как доказательства; разные системы получают только нужную им часть.",
    focus: "FT живёт на Person, LT — на Deal, полный след — в Trace, digital journey — в GA4.",
    nodes: [
      n("a-source", "traffic-sources", 0, 150),
      n("a-rule", "attribution-contract", 300, 150),
      n("a-surfaces", "web-surfaces", 600, 0),
      n("a-trace", "trace", 600, 300),
      n("a-ga4", "main-ga4", 900, 0),
      n("a-map", "source-map", 900, 300),
      n("a-pipe", "pipedrive", 1200, 300),
      n("a-prepared", "prepared-crm", 1500, 300),
      n("a-reports", "management-reports", 1800, 300),
    ],
    edges: [
      e("ae1", "a-source", "a-rule", "browser", "доказательства"),
      e("ae2", "a-rule", "a-surfaces", "browser", "UTM / referrer"),
      e("ae3", "a-rule", "a-trace", "server", "FT / LT / IDs"),
      e("ae4", "a-surfaces", "a-ga4", "browser", "digital journey"),
      e("ae5", "a-trace", "a-map", "business", "evidence"),
      e("ae6", "a-map", "a-pipe", "business", "FT Person / LT Deal"),
      e("ae7", "a-trace", "a-prepared", "report", "полный след"),
      e("ae8", "a-pipe", "a-prepared", "report", "CRM state"),
      e("ae9", "a-prepared", "a-reports", "report", "единая классификация"),
    ],
  },
  reporting: {
    label: "Отчётность",
    title: "Как лиды, расходы и поздние результаты сходятся в отчётах",
    description: "CRM определяет реальных лидов, рекламные API дают расходы, а GA4 показывает цифровой путь.",
    focus: "Ни одна система не заменяет остальные; общий результат строится из нескольких доказанных источников.",
    nodes: [
      n("r-ga4", "main-ga4", 0, 0),
      n("r-trace", "trace", 0, 190),
      n("r-pipe", "pipedrive", 0, 380),
      n("r-prepared", "prepared-crm", 390, 190),
      n("r-costs", "ad-costs", 780, 0),
      n("r-reports", "management-reports", 780, 260),
      n("r-future", "future-outcomes", 1170, 0),
      n("r-revenue", "revenue-reporting", 1560, 130),
    ],
    edges: [
      e("re1", "r-trace", "r-prepared", "report", "источник"),
      e("re2", "r-pipe", "r-prepared", "report", "CRM-результат"),
      e("re3", "r-prepared", "r-reports", "report", "реальные лиды"),
      e("re4", "r-ga4", "r-reports", "report", "digital journey"),
      e("re5", "r-costs", "r-reports", "report", "расход"),
      e("re6", "r-future", "r-revenue", "planned", "поздние outcomes"),
      e("re7", "r-reports", "r-revenue", "planned", "единая цепочка"),
    ],
  },
  roadmap: {
    label: "Следующие этапы",
    title: "Переход от рабочего лида к сквозной аналитике",
    description: "Что уже работает, что подготовлено и какие зависимости должны закрыться дальше.",
    focus: "Текущий этап доказал generate_lead; следующая практическая работа — sign_up и start_trial из платформы.",
    nodes: [
      n("m-foundation", "measurement-best-practices", 0, 160),
      n("m-lead", "generate-lead", 300, 0),
      n("m-defs", "custom-definitions", 300, 320),
      n("m-signup", "sign-up", 600, 0),
      n("m-trial", "start-trial", 600, 320),
      n("m-surfaces", "firebase-app", 900, 0),
      n("m-consent", "consent", 900, 320),
      n("m-future", "future-outcomes", 1200, 0),
      n("m-costs", "ad-costs", 1200, 320),
      n("m-revenue", "revenue-reporting", 1500, 160),
    ],
    edges: [
      e("me1", "m-foundation", "m-lead", "business", "этапы 1–2"),
      e("me2", "m-foundation", "m-defs", "business", "этап 2"),
      e("me3", "m-lead", "m-signup", "planned", "этап 3"),
      e("me4", "m-defs", "m-trial", "planned", "этап 3"),
      e("me5", "m-signup", "m-surfaces", "planned", "этап 4"),
      e("me6", "m-trial", "m-consent", "planned", "политика данных"),
      e("me7", "m-surfaces", "m-future", "planned", "этап 5"),
      e("me8", "m-consent", "m-costs", "planned", "Ads feedback"),
      e("me9", "m-future", "m-revenue", "planned", "этапы 5–7"),
      e("me10", "m-costs", "m-revenue", "planned", "расход + результат"),
    ],
  },
};

export const viewOrder: ViewKey[] = [
  "overview",
  "visit",
  "lead",
  "events",
  "attribution",
  "reporting",
  "roadmap",
];
